# Site settings
title: Caramel cc Cookie's github pages
email: CaramelccCookie at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  21 years old(not Korean age), Korean, Major in EECS

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: CaramelccCookie
github_username:  CaramelccCookie

# Build settings
markdown: kramdown
